### ISSUE TITLE
Error while requesting an access token: {"error":"consent_required"}

### ISSUE THREAD

**Issue by gvasas13** [docusign/eg-01-ruby-jwt#6]
Having a tough time figuring out what step I'm missing here.

I've been running plenty of tests successfully in dev and I'm currently trying to promote to our prod environment.

I'm providing a prod base url that I received from support https://na3.docusign.net/restapi/v2/

I've promoted my integrator key, I got a new public and private key text file. I've gone through the url granting permissions for signature and impersonation. I'm using my prods userid and the same structural code I had that worked fine in dev. (I'm 99% sure theres just some step or checkbox that I would have to complete on the website for this to work since I'm fairly confident in the code)

The only thing I believe I'm missing is a step where I say its ok to impersonate the admin users specific login. I've seen it mentioned in help files to use the Organization Administrators screen to easily push out impersonation privileges for every user (But as far as I can  tell that screen doesn't even exist) 

If anyone has been here before and has any ideas I would really appreciate any help or feedback you give.

Thank you very much!

**Comment by LarryKlugerDS** [comment]
Hi @gvasas13 ,

I'm sorry that I didn't see your message until now. StackOverflow with tag `docusignapi` is a good place to ask these types of questions.

`consent_required` is the expected response for the JWT flow until the person being impersonated has granted consent or until the administrator for the organization has granted consent at the organization level.

During development, the usual tactic is to have the person being impersonated grant individual consent. This is done by the person using the first leg of the oauth authorization code flow. The person being impersonated simply enters the url to a browser, authenticates, then grants consent.

From that point forward, your application can use the jwt flow to obtain an access token by itself.

The url for individual consent includes your client id (integration key) and other information. See the code from the Node example: https://github.com/docusign/eg-01-node-jwt/blob/master/index.js#L70

**Comment by LarryKlugerDS** [comment]
Please comment on this issue if you'd like it to be re-opened.
Thank you.
