### ISSUE TITLE
Error while requesting token: invalid_grant

### ISSUE THREAD

**Issue by pat-whitrock** [docusign/eg-01-ruby-jwt#8]
Hello!

I'm trying to run the examples. I've set up `ds_config.rb` as per instructions. When I run it I get:

```
Sending an envelope...
Starting up: fetching token
DocuSign SDK Error!
   code: 400
   message: {"error":"invalid_grant"}
```

I have set up an organization, authorized it as an admin, and updated it with the following permissions: `signature impersonation`. I found https://github.com/docusign/eg-01-node-jwt/issues/1 and I have set the integration key as the client id, so that doesn't appear to be the issue.

Do you now what may be the issue here? Or do you have any suggestions to continue debugging?

**Comment by InbarGazit** [comment]
Pat, this error can be caused for a variety of reasons, please confirm:
1. You have the UserID (not accountID!) of the user you're impersonting correctly, it's a GUID.
2. You have the private part of the RSA keypair, you use it exactly as you copied it with new lines etc. unchanged/touched
3. Your IK is defined correctly in the demo (sandbox) env and that's where you point.
4. User provided consent. You have to do that once.

**Comment by pat-whitrock** [comment]
Thanks for the quick response! Yes, as far as I can tell all four of those have been done correctly. I have gone through the process of setting up multiple apps in the demo environment following these instructions, but I encounter the same error each time.

**Comment by LarryKlugerDS** [comment]
Hi @pat-whitrock , are you still having this issue?
